spool c:\store_schema.txt
set echo on

-- This script should be run by the system user
CONNECT system/password;


DROP USER invoices CASCADE;

CREATE USER invoices IDENTIFIED BY invoices_password;

GRANT connect, resource TO invoices;

CONNECT invoices/invoices_password;

 
  CREATE TABLE "BUYERS" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"BUYER_ADRESS" VARCHAR2(255 CHAR), 
	"BUYER_NAME" VARCHAR2(255 CHAR), 
	"BUYER_NIP" NUMBER(19,0), 
	 PRIMARY KEY ("ID")
   );
  
  
  CREATE TABLE "SELLERS" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"SELLER_ADRESS" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"SELLER_COMPANY_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"SELLER_NIP" NUMBER(19,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
   );
  
  CREATE TABLE "ITEMS" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ITEM_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ITEM_PRICE" FLOAT(126) NOT NULL ENABLE, 
	"ITEM_QUANTITY" NUMBER(10,0) NOT NULL ENABLE, 
	"ITEM_VAT" NUMBER(10,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID"));

  CREATE TABLE "INVOICES" 
   (	"INVOICE_NO" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"INVOICE_DATE" DATE, 
	"PRICE_BRUTTO" FLOAT(126), 
	"BUYER_ID" NUMBER(19,0), 
	"ITEM_ID" NUMBER(19,0), 
	"SELLER_ID" NUMBER(19,0),
	 CONSTRAINT FK_BUYER FOREIGN KEY (BUYER_ID)
REFERENCES BUYERS(ID),
 CONSTRAINT FK_ITEMS FOREIGN KEY (ITEM_ID)
REFERENCES ITEMS(ID),
CONSTRAINT FK_SELLER FOREIGN KEY (SELLER_ID)
REFERENCES SELLERS(ID),
PRIMARY KEY ("INVOICE_NO")
   );
   
   COMMIT;
spool off
